//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarcacionesDll {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class conf : global::System.Configuration.ApplicationSettingsBase {
        
        private static conf defaultInstance = ((conf)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new conf())));
        
        public static conf Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\DesarrolloSw\\bddMarcaciones\\EnvioMarcacionesSAP\\Marcaciones")]
        public string SapFolder {
            get {
                return ((string)(this["SapFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'2019/12/19\',\'2020/01/09\',\'2020/01/28\',\'2020/02/10\'")]
        public string omitirFechas {
            get {
                return ((string)(this["omitirFechas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("((Hour(CHECKTIME)=7 and Minute(CHECKTIME)>34) or Hour(CHECKTIME) in (8,9))")]
        public string condicionAtraso {
            get {
                return ((string)(this["condicionAtraso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\DesarrolloSw\\bddMarcaciones\\bddBiometricoPifo.mdb")]
        public string bddPifoPath {
            get {
                return ((string)(this["bddPifoPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\DesarrolloSw\\bddMarcaciones\\bddBiometricoPuembo.mdb")]
        public string bddPuemboPath {
            get {
                return ((string)(this["bddPuemboPath"]));
            }
        }
    }
}
